### ISSUE TITLE
Preview 3D node dont refresh when the node is out of the screen

### ISSUE THREAD

**Issue by DorotaLuna** [MrForExample/ComfyUI-3D-Pack#111]
Here is my workspace look like:
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/122320001/269d5f9f-0e3f-42ea-9194-83a04155bde0)

The preview node is on the right out of the screen,
and when I refresh the page or opend another page.

The preview node isnt refresh and keeps on the top
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/122320001/4a4946f4-0fb1-4c8f-8475-b54595a79be3)

So most time I have to hide it from console then move the screen to node
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/122320001/35901df1-5f90-4455-a41b-d8c025d71b57)

**Comment by MrForExample** [comment]
Hi @DorotaLuna 
Sorry for the trouble
I'm not sure how I can reproduce this problem, also I'm sure I understand what you mean by "keeps on the top", can you give a little more information for it? Or even better if you can record a video for it pls?
Because when I refresh the page in Firefox the content inside preview node will be reset to empty, now you mentioned that is probably better it can keep the content is that what you mean?

**Comment by DorotaLuna** [comment]
Hi @MrForExample 
Here is the video:

https://github.com/MrForExample/ComfyUI-3D-Pack/assets/122320001/b73884e0-56ca-4137-87a1-c5c042121140

**Comment by MrForExample** [comment]
> Hi @MrForExample Here is the video:
> 
>  2024-03-20.11-31-18.mp4

Oh, I see, thanks for testing, this is an edge case I didn't notice, I'll fix it in next update, cheers 👍
