### ISSUE TITLE
Suggestions for zero123plus multi-view nodes

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#191]
It is hoped that a campos input can be added.
The generated multi-view edges are incomplete and seem to be clipped.
![FKP@3Q52(GC @2MV{EL~QQ](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/46019416/030411ef-0357-4829-b7b6-0ee32a745f2f)

**Comment by MrForExample** [comment]
Hi, good day to you, sorry, there is no way for me to add campos input to Zero123++ model without training a new model, as it is trained to generated set of multi-view images from pre-defined views.

Also, image incomplete and clipping you are experiencing is due to Zero123++ training settings, again you have to fine-tune or train a new model to address it.

Cheers

**Comment by 807502278** [comment]
Oh, I'm sorry, I thought zero123plus was the same as zero123
