### ISSUE TITLE
Use our own images of 4 angles with large multiview gaussian model ?

### ISSUE THREAD

**Issue by al3dv2** [MrForExample/ComfyUI-3D-Pack#26]
It would be great if we could use our own images of 4 angles with large multiview gaussian model, someone know how to do it in comfyui ?

**Comment by MrForExample** [comment]
Just replace the input images to large multiview gaussian model with your own images and that's it.

For the best result make sure:
1. your multiview images height == width
2. your images is in correct view order (you can check with preview image node)

**Comment by al3dv2** [comment]
I tried but I've a error message when I put the input directly on the multiview gaussian model : 
![3mv](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/96b18d93-6602-4e0b-bf14-67074a326419)
![2mv](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/1d1167c7-82cd-463d-a0d1-0e5abf0d8c84)
![1mv](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/79b9d641-55d2-41c1-acd0-176df61b5e30)

**Comment by al3dv2** [comment]
Apparently it's a size problem I've try 512x512 and 256x256

**Comment by al3dv2** [comment]
I put a image example I've generate with sd if you want to try 

![opaciterversion](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/19b3190c-de4c-4e37-80a1-658c0b1e65df)

**Comment by MrForExample** [comment]
You get input size mismatch problem error, because you are loading a single image instead of four images, if you preview the output of the MVDreamer Model node you'll see what it meant, 
You need to use load images node instead of load image. something like this:
![Screenshot 2024-02-10 173941](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/62230687/d38fcc93-2b1f-4947-b34a-2c029a02dca4)
And put your images inside the corresponding input folder in a correct order

**Comment by al3dv2** [comment]
Thanks it's works !

**Comment by al3dv2** [comment]
Thanks it's works !

**Comment by al3dv2** [comment]
Just a last question do you know how I can change the seed and the inference steps ? thanks

**Comment by MrForExample** [comment]
> Just a last question do you know how I can change the seed and the inference steps ? thanks

About inference steps, there is no inference steps parameters in LGM, its Asymmetric U-Net did not use denoise but predict gaussians features in one pass.

About seed, I believe we can add seed to the MVDreamer but not LGM (again, since there is no denoise), I'll add it to the project in the next update

Cheers friend, thanks for the effort, have a good day 👍
