### ISSUE TITLE
Where can I find models of T2I V2 and V3?

### ISSUE THREAD

**Issue by jakechai** [MrForExample/ComfyUI-3D-Pack#311]
Where can I find models of CRM T2I V2 and V3?
![missing](https://github.com/user-attachments/assets/1b1f11c7-da91-489f-b463-577102862463)

**Comment by MrForExample** [comment]
Haha, you are the first to noticed :) that's a PBR textures generation model I'm researching and training myself, and haven't finish it yet, but almost, I may release it after a month or two along with research paper for the whole development process.
Cheers, have a good day 👍

**Comment by jakechai** [comment]
Great! I can't wait to try it. I have some thoughts about your texture projection process. We don't need to make 2nd mesh and texture refinement in 3D software if you could make all these happen.

1. Can you add an orthographic camera switch for Mesh Orbit Renderer and Explicit Target Color  Projection? In some cases, orthographic projection is much better than perspective one. That is a 90 FOV orthographic camera with a Target Distance of 1.0 and a radius of 2.0 based on a 1.0 unit cube, which is the CRM algorithm (the following image). This is based on my experiences on the UE texture projection project.
![crm camera](https://github.com/user-attachments/assets/aa38facc-eb3b-4f13-a60e-041d8a07153f)

https://github.com/user-attachments/assets/28311bdb-ea41-4904-a202-452a598fcddb

2. Is it possible to bake all the PBR textures such as Albedo, Roughness, and Normal, (Metallic, AO, Cavity, etc.) at the same time? All of them can be converted from the Albedo texture using different methods. One of my favorites is [Materialize](https://boundingboxsoftware.com/materialize/). 
![materialize](https://github.com/user-attachments/assets/0ec27295-ce9c-4754-8678-e05fd1be4b3b)

3. Because we need mesh optimization before the texture projection process. Can you bring [Mesh Anything](https://github.com/buaacyw/MeshAnything) the powerful mesh optimization algorithm into the 3D Pack world? This will make the 3D pack a more complete and practical toolkit for model reconstruction.

**Comment by MrForExample** [comment]
Hi @jakechai 
1. I'll see if I can add that orthographic camera switch for Mesh Orbit Renderer and Explicit Target Color Projection
2. Right now, the Mesh class can only support single UV and single Albedo, single Metallic (Blue channel) & Roughness (Green channel) map, so as right now, Explicit Target Color Projection node support those three types of maps, I do have plan to extend the Mesh class's functionality more in the future
3. I have tried Mesh Anything multiple times before, so it's my colleagues, for both v1 and v2, but we all think it doesn't work as robust as advertised, most meshes are kind of unusable, so that is on hold as for now.

Hi @GeorgeSte thanks for the kind words, it uses 6 orthogonal MV normals to condition the shape, and one front view images to condition the appearance, and generate 6X3 MV views for Albedo, Metallic and Roughness respectively
