### ISSUE TITLE
how to avoid miniconda?

### ISSUE THREAD

**Issue by klinter007** [MrForExample/ComfyUI-3D-Pack#48]
I don't have miniconda installed on my system and i use venv from python to run my comfy
is it possible to run this repo?
if so, can I have a guide to install it please?

**Comment by MrForExample** [comment]
When I trying to install it using venv, I keep getting CUDA build error, that's why I'm using miniconda at first place, because it's a competent python environment manager that solves those dependency issue across different OS.

If you are on Windows then you can use [Chocolatey](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#setup-method-1-using-chocolatey-windows-only).

**Comment by vicentecarro** [comment]
Don't know about @klinter007 but my problem with miniconda is that it's not official or standard in ubuntu 23.10. I cannot find it with apt-cache search or the general package manager or anywhere else, so simply put, I don't trust it. I'll wait to an alternative method in the future, if any.
